#!/sbin/sh

# trigger red LED
echo '255' > /sys/class/leds/red/brightness
# trigger button-backlight
echo '255' > /sys/class/leds/button-backlight/brightness
# trigger vibrator
echo "200" > /sys/class/timed_output/vibrator/enable

cat /dev/input/event1 > /dev/keycheck&
sleep 3

# trigger red LED
echo '0' > /sys/class/leds/red/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/button-backlight/brightness

kill -9 $!

if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
# fixing CPU clocks to avoid issues in recovery
echo 921600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245760 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

# correct LCD-backlight brightness
echo '150' > /sys/class/leds/lcd-backlight/brightness

# USB fixup "mass_storage, adb"
TAG="usb"
VENDOR_ID=0FCE
PID_PREFIX=6
USB_FUNCTION=mass_storage,adb
# generate PID based on build.prop
PID_SUFFIX_PROP=$(/system/bin/getprop persist.usb.pid_suffix)
PID=${PID_PREFIX}${PID_SUFFIX_PROP}
# hardcoded PID for ARC
#PID=614F
# hardcoded PID for PLAY
#PID=615D
# hardcoded PID for RAY
#PID=6161
echo 0 > /sys/class/android_usb/android0/enable
echo ${VENDOR_ID} > /sys/class/android_usb/android0/idVendor
echo ${PID} > /sys/class/android_usb/android0/idProduct
/system/bin/log -t ${TAG} -p i "usb product id: ${PID}"
echo ${USB_FUNCTION} > /sys/class/android_usb/android0/functions
/system/bin/log -t ${TAG} -p i "enabled usb functions: ${USB_FUNCTION}"
echo 1 > /sys/class/android_usb/android0/enable
/system/bin/setprop sys.usb.state ${USB_CONFIG_PROP}

rm /cache/recovery/boot
mount -o remount,rw rootfs /
umount -l /system
umount -l /data
umount -l /cache
umount -l /sdcard
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery&
/sbin/adbd recovery
fi

#continue booting

