#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 768000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245760 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

echo 0 > /sys/class/android_usb/android0/enable
echo 0FCE > /sys/class/android_usb/android0/idVendor
echo 6161 > /sys/class/android_usb/android0/idProduct
echo mass_storage,adb > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
stop adbd

# trigger gold LED
echo '0' > /sys/class/leds/red/brightness
echo '150' > /sys/class/leds/green/brightness
echo '255' > /sys/class/leds/blue/brightness
# trigger button-backlight
echo '255' > /sys/class/leds/button-backlight/brightness
# trigger vibrator
echo '200' > /sys/class/timed_output/vibrator/enable
cat /dev/input/event1 > /dev/keycheck&
sleep 3
# trigger gold LED
echo '0' > /sys/class/leds/red/brightness
echo '0' > /sys/class/leds/green/brightness
echo '0' > /sys/class/leds/blue/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/button-backlight/brightness

kill -9 $!
